export enum DBTables {
    Users = 'users',
    UsersEntries = 'users_entries',
    AccountImages = 'account_images',
    Themes = 'themes',
    Languages = 'languages',
    Courses = 'courses',
    CoursesData = 'courses_data',
    UsersCourses = 'users_courses',
    CoursesPictures = 'courses_pictures',
    CoursesColorPalettes = 'courses_color_palettes',
    CoursesItems = 'courses_items',
    CoursesItemsAttachments = 'courses_items_attachments',
    Chats = 'chats',
    ChatsImages = 'chats_images',
    UsersChats = 'users_chats',
    Messages = 'messages',
    MessagesStatuses = 'messages_statuses',
    DaysOfTheWeek = 'days_of_the_week',
    TimetableItems = 'timetable_items',
    TimetableItemGroups = 'timetable_item_groups',
    TimetableItemStickers = 'timetable_item_stickers',
    TimetableItemsTimetableItemsStickers = 'timetable_items_timetable_items_stickers',
    UsersTimetableItemsStickers = 'users_timetable_items_stickers',
}

export enum SwaggerTags {
    Login = 'Login',
    Logout = 'Logout',
    Users = 'Users',
    Courses = 'Courses',
    CourseItems = 'CourseItems',
    Chats = 'Chats',
    Files = 'Files',
    Timetable = 'Timetable',
}
